# Skyeng API Configuration
skyeng:
  api:
    base-url: https://dictionary.skyeng.ru
  gateway:
    base-url: https://dictionary-gateway.skyeng.ru
    popularity-update:
      min-request-delay-ms: 1000
      max-request-delay-ms: 2000
      error-delay-ms: 180000

# Server Configuration
server:
  port: 8080

# Database Configuration
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/learn_en_word
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
#    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
#        format_sql: true
        jdbc:
          lob:
            non_contextual_creation: true
  cache:
    jcache:
      config: classpath:ehcache.xml

# Logging Configuration
logging:
  file:
    name: ${LOG_FILE:logs/learn-en-word.log}
  logback:
    rollingpolicy:
      file-name-pattern: ${LOG_FILE_PATTERN:${LOG_FILE:logs/learn-en-word.log}.%d{yyyy-MM-dd}.%i.gz}
      max-file-size: ${LOG_MAX_FILE_SIZE:10MB}
      max-history: ${LOG_MAX_HISTORY:30}
      total-size-cap: ${LOG_TOTAL_SIZE_CAP:1GB}
      clean-history-on-start: false
  level:
    root: INFO
#    com.zoirs.learn_en_word: DEBUG
#    org.hibernate.SQL: DEBUG
#    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
