# Skyeng API Configuration
skyeng:
  api:
    base-url: https://dictionary.skyeng.ru
  gateway:
    base-url: https://dictionary-gateway.skyeng.ru
    popularity-update:
      startup-delay-ms: 30000
      min-request-delay-ms: 10000
      max-request-delay-ms: 60000
      error-delay-ms: 180000

# Server Configuration
server:
  port: 8080

# Database Configuration
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/learn_en_word
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
#    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
#        format_sql: true
        jdbc:
          lob:
            non_contextual_creation: true
  cache:
    jcache:
      config: classpath:ehcache.xml

# Logging Configuration
logging:
  level:
    root: INFO
#    com.zoirs.learn_en_word: DEBUG
#    org.hibernate.SQL: DEBUG
#    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
